import React from 'react'
import image1 from "../Asset/image1.jpg"
import image2 from "../Asset/image2.jpg"
import image3 from "../Asset/image3.jpg"
import image4 from "../Asset/image4.jpg"
import image5 from "../Asset/image5.jpg"
import image6 from "../Asset/image6.jpg"
import image7 from "../Asset/image7.jpg"
import image8 from "../Asset/image8.jpg"
import image9 from "../Asset/image9.jpg"
import image10 from "../Asset/image10.jpg"
import image11 from "../Asset/image11.jpg"
import image12 from "../Asset/image12.jpg"
import image13 from "../Asset/image13.jpg"
import image14 from "../Asset/image14.jpg"
import image15 from "../Asset/image15.jpg"
import image16 from "../Asset/image16.jpg"
import image17 from "../Asset/image17.jpg"
import image18 from "../Asset/image18.jpg"
import image19 from "../Asset/image19.jpg"
import image20 from "../Asset/image20.jpg"
import image21 from "../Asset/image21.jpg"
import image22 from "../Asset/image22.jpg"
import image23 from "../Asset/image23.jpg"
const ShopingItems =[
{
    id:1,
    name: "Modern Poster",
    amount: 30.99,
    image: image1,
    category: "living room",
    company: "liddy",
    color: ["black"],
    shipping: true,
    Available : "In Stock",
    SKU : "RecQ0fMd8T0Vk211E"
},
{
    id:2,
    name: "Bar Stool",
    amount: 40.99,
    image: image2,
    category: "dining",
    company: "liddy",
    color: ["black"],
    Available : "In Stock",
    SKU : "RecoM2MyHJGHLVi5l",

},
{
    id:3,
    name: "Armchair",
    amount: 125.99,
    image: image3,
    category: "bedroom",
    company: "macros",
    color: ["green", "black"],
    shipping: true,
    Available : "In Stock",
    SKU : "Recd1jIVIEChmiwhe",
},
{
    id:4,
    name: "Suede Armchair",
    amount: 159.99,
    image: image4,
    category: "office",
    company: "caressa",
    color: ["yellow"],
    Available : "In Stock",
    SKU : "RecroK1VD8qVdMP5H",
},
{
    id:5,
    name: "Leather Chair",
    amount: 200.99,
    image: image5,
    category: "bedroom",
    company: "caressa",
    color: ["red", "green", "yellow"],
    Available : "In Stock",
    SKU : "RecoW8ecgjtKx2Sj2",
},
{
    id:6,
    name: "Emperor Bed",
    amount: 239.99,
    image: image6,
    category: "bedroom",
    company: "ikea",
    color:[ "black"],
    shipping: true,
    Available : "Out Of Stock",
    SKU : "Rec1Ntk7siEEW9ha1",
},
{
    id:7,
    name: "Accent Chair",
    amount: 259.99,
    image: image7,
    category: "office",
    company: "macros",
    color:["red","green", "blue"],
    shipping: true,
    Available : "In Stock",
    SKU : "RecZkNf2kwmdBcqd0",
},
{
    id:8,
    name: "Shelf",
    amount: 309.99,
    image: image8,
    category: "living room",
    company: "ikea",
    color: ["green"],
    Available : "In Stock",
    SKU : "Rec7CjDWKRgNQtrKe",

},
{
    id:9,
    name: "Modern Bookshelf",
    amount: 319.99,
    image: image9,
    category: "kids",
    company: "caressa",
    color: ["red", "green", "yellow"],
    Available : "In Stock",
    SKU : "Rec7CjDWKRgNQtrKe",
},
{
    id:10,
    name: "High-Back Bench",
    amount: 399.99,
    image: image10,
    category: "office",
    company: "ikea",
    color: ["green", "black"],
    shipping: true,
    Available : "In Stock",
    SKU : "Recrfxv3EwpvJwvjq",
},
{
    id:11,
    name: "Wooden Desk",
    amount: 400.99,
    image: image11,
    category: "office",
    company: "ikea",
    color: ["green", "blue"],
    Available : "In Stock",
    SKU : "Recm7wC8TBVdU9oEL",
},
{
    id:12,
    name: "Dining Table",
    amount: 429.99,
    image: image12,
    category: "dining",
    company: "ikea",
    color: ["red", "green", 'blue'],
    shipping: true,
    Available : "In Stock",
    SKU : "RecotY5Nh00DQFdkm",
},
{
    id:13,
    name: "Entertainment Center",
    amount: 599.99,
    image: image13,
    category: "living room",
    company: "caressa",
    color: ["red", "black"],
    shipping: true,
    Available : "In Stock",
    SKU : "RecNZ0koOqEmilmoz",
},
{
    id:14,
    name: "Utopia Sofa",
    amount: 799.99,
    image: image14,
    category: "living room",
    company: "liddy",
    color: ["red", "green"],
    Available : "In Stock",
    SKU : "Rec7JInsuCEHgmaGe",
},
{
    id:15,
    name: "Leather Sofa",
    amount: 999.99,
    image: image15,
    category: "office",
    company: "caressa",
    color: ["green", "blue"],
    Available : "In Stock",
    SKU : "RecEOA6qtDag1hRbU",
},
{
    id:16,
    name: "Albany Sectional",
    amount: 1099.99,
    image: image16,
    category: "living room",
    company: "liddy",
    color: ["black", "yellow"],
    Available : "Out Of Stock",
    SKU : "RecEHmzvupvT8ZONH",

},
{
    id:17,
    name: "Simple Chair",
    amount: 1099.99,
    image: image17,
    category: "living room",
    company: "liddy",
    color: ["blue"],
    shipping: true,
    Available : "In Stock",
    SKU : "RecF0KpwlkF7e8kXO",
},
{
    id:18,
    name: "Vase Table",
    amount: 1209.99,
    image: image18,
    category: "office",
    company: "macros",
    color: ["red"],
    Available : "In Stock",
    SKU : "Rec3jeKnhInKHJuz2",
},
{
    id:19,
    name: "Sofa Set",
    amount: 1299.99,
    image: image19,
    category: "living room",
    company: "macros",
    color: ["green", "yellow"],
    shipping: true,
    Available : "In Stock",
    SKU : "Recs5BSVU3qQrOj4E",
},
{
    id:20,
    name: "Wooden Desk",
    amount: 1509.99,
    image: image20,
    category: "office",
    company: "ikea",
    color: ["black"],
    shipping: true,
    Available : "In Stock",
    SKU : "RecJIjREF3dlFi3sR",
},
{
    id:21,
    name: "Wooden Table",
    amount: 2349.99,
    image: image21,
    category: "kitchen",
    company: "caressa",
    color: ["red", "yellow"],
    shipping: true,
    Available : "In Stock",
    SKU : "RectfNsySwAJeWDN2",
},
{
    id:22,
    name: "Wooden Bed",
    amount: 2500.99,
    image: image22,
    category: "bedroom",
    company: "ikea",
    color: ["black", "yellow"],
    Available : "In Stock",
    SKU : "Recv2ohxljlK2FZO7",
},
{
    id:23,
    name: "Albany Table",
    amount: 3099.99,
    image: image23,
    category: "kitchen",
    company: "liddy",
    color: ["blue", "yellow"],
    Available : "In Stock",
    SKU : "Rec5NBwZ5zCD9nfF0",
},
]

export default ShopingItems